#!/bin/bash
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
update-alternatives --set python3 /usr/bin/python3.8
wget -O /var/tmp/bazel-3.7.1-installer-linux-x86_64.sh https://github.com/bazelbuild/bazel/releases/download/3.7.1/bazel-3.7.1-installer-linux-x86_64.sh
chmod +x /var/tmp/bazel-3.7.1-installer-linux-x86_64.sh
/var/tmp/bazel-3.7.1-installer-linux-x86_64.sh
pip3 install -r /opt/client_side_encryption/pip3_requirements.txt
